# Generated by Django 4.0.4 on 2022-07-05 23:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import servicios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('t_toque', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha y hora parte')),
                ('tipo_convocatoria', models.CharField(blank=True, choices=[('r', 'Radiollamado'), ('t', 'Toque de sirena')], max_length=1, verbose_name='Tipo convocatoria')),
                ('f_salida', models.DateField(default=datetime.date.today, verbose_name='Fecha salida')),
                ('h_salida', models.TimeField(blank=True, null=True, verbose_name='Hora salida')),
                ('f_llegada', models.DateField(default=datetime.date.today, null=True, verbose_name='Fecha arribo')),
                ('h_llegada', models.TimeField(blank=True, null=True, verbose_name='Hora arribo')),
                ('n_servicio', models.AutoField(primary_key=True, serialize=False, verbose_name='Servicio N°')),
                ('solicitante', models.CharField(blank=True, max_length=50, verbose_name='Nombre solicitante')),
                ('dni_solicitante', models.IntegerField(blank=True, null=True, verbose_name='DNI')),
                ('tel_solicitante', models.IntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('zona', models.CharField(blank=True, choices=[('u', 'Urbana'), ('r', 'Ruta')], max_length=1)),
                ('provincia', models.CharField(blank=True, default='Buenos Aires', max_length=50)),
                ('ciudad', models.CharField(blank=True, default='Punta Alta', max_length=50)),
                ('calle', models.CharField(blank=True, max_length=50)),
                ('numero', models.SmallIntegerField(blank=True, null=True)),
                ('entre_calles', models.CharField(blank=True, max_length=80)),
                ('ruta', models.CharField(blank=True, max_length=20)),
                ('km', models.SmallIntegerField(blank=True, null=True)),
                ('propietario', models.CharField(blank=True, max_length=50, verbose_name='Nombre propietario')),
                ('dni_propietario', models.IntegerField(blank=True, null=True, verbose_name='DNI')),
                ('tel_propietario', models.IntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('dom_propietario', models.CharField(blank=True, max_length=60, verbose_name='Domicilio')),
                ('seguro', models.CharField(blank=True, max_length=50)),
                ('n_poliza', models.IntegerField(blank=True, null=True, verbose_name='N° poliza')),
                ('metodo_ataque', models.CharField(blank=True, max_length=50)),
                ('obs', models.TextField(blank=True, verbose_name='Observaciones')),
                ('tipo', models.CharField(blank=True, choices=[('V', 'VIVIENDA'), ('F', 'FORESTAL'), ('A', 'ACCIDENTE'), ('R', 'RESCATE'), ('C', 'COLABORACION'), ('I', 'INUNDACION'), ('D', 'DESASTRE')], max_length=1, null=True, verbose_name='Tipo servicio')),
                ('personal', models.ManyToManyField(blank=True, related_name='personal', to=settings.AUTH_USER_MODEL)),
                ('vehiculos', models.ManyToManyField(blank=True, to='sistema.unidades')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenes', models.ImageField(upload_to=servicios.models.path_fotos)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicios')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('n_asistencia', models.AutoField(primary_key=True, serialize=False, verbose_name='Asistencia N°')),
                ('t_asistencia_inicio', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha y hora de inicio')),
                ('t_asistencia_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora finalización')),
                ('motivo', models.CharField(blank=True, choices=[('A', 'ASISTENCIA'), ('C', 'CAPACITACIÓN'), ('C', 'CEREMONIAS'), ('O', 'OTROS')], max_length=1)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('personal_asistencia', models.ManyToManyField(blank=True, related_name='personal_asistencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
