# Generated by Django 4.0.4 on 2022-07-15 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_asistencias_motivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='dni_propietario',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='dom_propietario',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='n_poliza',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='propietario',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='seguro',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='tel_propietario',
        ),
        migrations.CreateModel(
            name='VehiculosInvolucrados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(blank=True, max_length=50)),
                ('marca', models.CharField(blank=True, max_length=30)),
                ('modelo', models.CharField(blank=True, max_length=30)),
                ('dominio', models.CharField(blank=True, max_length=30)),
                ('agno', models.IntegerField(null=True)),
                ('extra1', models.TextField(blank=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicios')),
            ],
        ),
        migrations.CreateModel(
            name='Involucrados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(blank=True, max_length=50)),
                ('razon', models.CharField(blank=True, max_length=50)),
                ('dni', models.IntegerField(blank=True, null=True, verbose_name='DNI')),
                ('tel_propietario', models.IntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('dom', models.CharField(blank=True, max_length=60, verbose_name='Domicilio')),
                ('extra', models.TextField(blank=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicios')),
            ],
        ),
    ]
