# Generated by Django 4.0.4 on 2022-07-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_rename_tel_propietario_involucrados_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='involucrados',
            name='extra',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='vehiculosinvolucrados',
            name='agno',
            field=models.IntegerField(null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='vehiculosinvolucrados',
            name='extra1',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='vehiculosinvolucrados',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo de vehículo'),
        ),
    ]
