# Generated by Django 4.0.4 on 2022-07-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_alter_involucrados_extra_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenes',
            options={'verbose_name': 'Imagen', 'verbose_name_plural': 'Imagenes'},
        ),
        migrations.AlterModelOptions(
            name='involucrados',
            options={'verbose_name': 'Persona involucrada', 'verbose_name_plural': 'Personas involucradas'},
        ),
        migrations.AlterModelOptions(
            name='vehiculosinvolucrados',
            options={'verbose_name': 'Vehiculo involucrado', 'verbose_name_plural': 'Vehiculos involucrados'},
        ),
    ]
