# Generated by Django 4.0.4 on 2022-07-01 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='cantidad_toques',
        ),
    ]
