# Generated by Django 4.0.4 on 2022-07-03 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_personal_cantidad_toques'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('S', 'SERVICIOS'), ('A', 'ASISTENCIAS'), ('O', 'ORDEN INTERNO'), ('S', 'GUARDIAS')], max_length=1)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
