# Generated by Django 4.0.4 on 2022-07-03 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_puntaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntaje',
            name='persona',
        ),
        migrations.AddField(
            model_name='personal',
            name='puntaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='puntaje',
            name='tipo',
            field=models.CharField(choices=[('S', 'SERVICIOS'), ('A', 'ASISTENCIAS'), ('O', 'ORDEN INTERNO'), ('G', 'GUARDIAS')], default='G', max_length=1),
        ),
    ]
