# Generated by Django 4.0.4 on 2022-07-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_personal_puntaje_puntaje_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntaje',
            name='persona',
        ),
        migrations.AddField(
            model_name='personal',
            name='puntaje',
            field=models.ManyToManyField(to='usuarios.puntaje'),
        ),
    ]
