# Generated by Django 4.0.4 on 2022-07-03 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_puntaje_persona_personal_puntaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='puntaje',
        ),
        migrations.AddField(
            model_name='personal',
            name='puntaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.puntaje'),
        ),
    ]
