# Generated by Django 4.0.4 on 2022-07-03 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_personal_puntaje_personal_puntaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='puntaje',
        ),
        migrations.DeleteModel(
            name='Puntaje',
        ),
    ]
