# Generated by Django 4.0.4 on 2022-07-06 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_personal_puntaje_delete_puntaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntaje',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('servicios', models.IntegerField(blank=True, default=0, null=True)),
                ('servicios_mensual', models.IntegerField(blank=True, default=0, null=True)),
                ('asistencias', models.IntegerField(blank=True, default=0, null=True)),
                ('asistencias_mensual', models.IntegerField(blank=True, default=0, null=True)),
                ('guardias', models.IntegerField(blank=True, default=0, null=True)),
                ('guardias_mesual', models.IntegerField(blank=True, default=0, null=True)),
                ('orde', models.IntegerField(blank=True, default=0, null=True)),
                ('orden_mensual', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
