# Generated by Django 4.0.4 on 2022-07-07 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_puntaje_options_rename_orde_puntaje_orden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puntaje',
            old_name='orden',
            new_name='orden_interno',
        ),
        migrations.RenameField(
            model_name='puntaje',
            old_name='orden_mensual',
            new_name='orden_interno_mensual',
        ),
    ]
