# Generated by Django 4.0.4 on 2022-07-07 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_rename_orden_puntaje_orden_interno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puntaje',
            old_name='guardias_mesual',
            new_name='guardias_mensual',
        ),
    ]
