# Generated by Django 4.0.4 on 2022-07-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_rename_guardias_mesual_puntaje_guardias_mensual'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Puntaje',
        ),
    ]
