# Generated by Django 4.0.4 on 2022-07-07 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_alter_puntajes_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntajes',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
