# Generated by Django 4.0.4 on 2022-07-07 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_gruposguardia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gruposguardia',
            name='miembros',
        ),
        migrations.AddField(
            model_name='gruposguardia',
            name='miembros',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to=settings.AUTH_USER_MODEL),
        ),
    ]
