# Generated by Django 4.0.4 on 2022-07-08 00:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_remove_gruposguardia_miembros_gruposguardia_miembros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gruposguardia',
            name='miembros',
        ),
        migrations.AddField(
            model_name='gruposguardia',
            name='miembros',
            field=models.ManyToManyField(blank=True, related_name='miembros', to=settings.AUTH_USER_MODEL),
        ),
    ]
