# Generated by Django 4.0.4 on 2022-07-08 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0025_remove_puntajes_persona_personal_puntajes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='puntajes',
        ),
        migrations.AddField(
            model_name='puntajes',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='persona', to=settings.AUTH_USER_MODEL),
        ),
    ]
