# Generated by Django 4.0.4 on 2022-07-12 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0026_remove_personal_puntajes_puntajes_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('finalizacion', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('A', 'Anual'), ('C', 'Casamiento'), ('E', 'Estudio'), ('I', 'Enfermedad'), ('F', 'Fallecimiento de Familiar'), ('N', 'Nacimiento'), ('P', 'Embarazo')], max_length=1)),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
