# Generated by Django 4.0.4 on 2022-07-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0027_licencias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licencias',
            options={'verbose_name': 'Licencia', 'verbose_name_plural': 'Licencias'},
        ),
        migrations.AlterField(
            model_name='licencias',
            name='finalizacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='licencias',
            name='inicio',
            field=models.DateField(),
        ),
    ]
