# Generated by Django 4.0.4 on 2022-07-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0028_alter_licencias_options_alter_licencias_finalizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='jerarquia',
            field=models.IntegerField(choices=[(1, 'ASPIRANTE'), (2, 'BOMBERO'), (3, 'SUBOF. SUBAYUDANTE'), (4, 'SUBOF. AYUDANTE'), (5, 'SUBOF. AYUDANTE DE 1RA'), (6, 'SUBOF. AYUDANTE PRINCIPAL'), (7, 'SUBOF. AYUDANTE MAYOR'), (8, 'OF. 3ERO'), (9, 'OF. 2DO'), (10, 'OF. 1ERO'), (11, 'SUBCOMANDANTE'), (12, 'COMANDANTE'), (13, 'COMANDANTE MAYOR'), (14, 'COMANDANTE GENERAL')], null=True),
        ),
    ]
