# Generated by Django 4.0.4 on 2022-07-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0029_alter_personal_jerarquia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gruposguardia',
            options={'ordering': ['miembros__jerarquia'], 'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
    ]
