# Generated by Django 4.0.4 on 2022-07-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0030_alter_gruposguardia_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gruposguardia',
            options={'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterField(
            model_name='gruposguardia',
            name='grupo',
            field=models.IntegerField(choices=[(1, 'GRUPO 1'), (2, 'GRUPO 2'), (3, 'GRUPO 3'), (4, 'GRUPO 4')], primary_key=True, serialize=False),
        ),
    ]
