# Generated by Django 4.0.4 on 2022-07-15 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0031_alter_gruposguardia_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'ordering': ('-jerarquia', 'fecha_alta'), 'verbose_name': 'Miembro', 'verbose_name_plural': 'Miembros'},
        ),
    ]
