# Generated by Django 4.0.4 on 2022-07-15 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0033_alter_gruposguardia_options_alter_personal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gruposguardia',
            options={'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
    ]
