# Generated by Django 4.0.4 on 2022-07-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0034_alter_gruposguardia_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'ordering': ('jerarquia', 'fecha_alta'), 'verbose_name': 'Miembro', 'verbose_name_plural': 'Miembros'},
        ),
    ]
