# Generated by Django 4.0.4 on 2022-07-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0035_alter_personal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'verbose_name': 'Miembro', 'verbose_name_plural': 'Miembros'},
        ),
    ]
