# Generated by Django 4.0.4 on 2022-07-21 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0039_alter_personal_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.IntegerField()),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=400)),
                ('adjunto', models.FileField(blank=True, null=True, upload_to=usuarios.models.path_sanciones)),
                ('sancionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sanción',
                'verbose_name_plural': 'Sanciones',
            },
        ),
    ]
