# Generated by Django 4.0.4 on 2022-07-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0040_sanciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('S', 'SOLTERO'), ('C', 'CASADO'), ('D', 'DIVORCIADO'), ('V', 'VIUDO')], max_length=1),
        ),
    ]
