# Generated by Django 4.0.4 on 2022-07-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0043_remove_personal_estudios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudios',
            name='tipo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
