# Generated by Django 4.0.4 on 2022-08-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0046_puntajes_agno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntajes',
            name='agno',
            field=models.IntegerField(default=2022, verbose_name='Año'),
        ),
    ]
