# Generated by Django 4.0.4 on 2022-08-04 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0047_alter_puntajes_agno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntajes',
            name='agno',
        ),
    ]
