# Generated by Django 4.0.4 on 2022-08-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0048_remove_puntajes_agno'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntajes',
            name='agno',
            field=models.IntegerField(default=2022),
        ),
    ]
