# Generated by Django 4.0.4 on 2022-06-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.SmallIntegerField()),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('agno', models.SmallIntegerField(verbose_name='Año')),
                ('proposito', models.CharField(choices=[('V', 'VIVIENDA'), ('F', 'FORESTAL'), ('R', 'RESCATE'), ('T', 'TRANSPORTE'), ('O', 'OTROS')], max_length=1)),
                ('dominio', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
            },
        ),
    ]
