# Generated by Django 4.0.4 on 2022-07-15 12:25

from django.db import migrations, models
import django.db.models.deletion
import sistema.models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidades',
            name='novedades',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='modelo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='ImagenesVehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenes', models.ImageField(upload_to=sistema.models.path_fotos)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.unidades')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
    ]
