# Generated by Django 4.0.4 on 2022-07-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_unidades_novedades_alter_unidades_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidades',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
