# Generated by Django 4.0.4 on 2022-07-22 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_documentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacion',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.datetime(2022, 7, 22, 3, 34, 21, 374141), verbose_name='Fecha publicación'),
        ),
    ]
