# Generated by Django 4.0.4 on 2022-07-22 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_alter_documentacion_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacion',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha publicación'),
        ),
    ]
